[package]
name = "query"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
db = { workspace = true }
derive_more = { workspace = true }
ic = { workspace = true }
orm = { workspace = true }
schema = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
strum = { workspace = true }
types = { workspace = true }
