[package]
name = "db"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
derive_more = { workspace = true }
ic = { workspace = true }
lib_cbor = { workspace = true }
lib_time = { workspace = true }
mimic_common = { workspace = true }
mimic_derive = { workspace = true }
serde = { workspace = true }
core_schema = { workspace = true }
snafu = { workspace = true }
orm = { workspace = true }
orm_schema = { workspace = true }
strum = { workspace = true }
types = { workspace = true }
