[package]
name = "canister_root"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
design = { workspace = true }
game = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
mimic = { workspace = true }
state = { workspace = true }

[build-dependencies]
design = { workspace = true }
mimic = { workspace = true }
mimic_base = { workspace = true }
