[package]
name = "types"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
derive_more = { workspace = true }
serde_bytes = { workspace = true }
serde = { workspace = true }
lib_time = { workspace = true }
lib_rand = { workspace = true }
snafu = { workspace = true }
rust_decimal = { workspace = true }
num-traits = { workspace = true }
mimic_common = { workspace = true }
mimic_derive = { workspace = true }
ulid = { workspace = true }
