[package]
name = "mimic"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
api = { workspace = true }
lib_ic = { workspace = true }
core_state = { workspace = true }
core_schema = { workspace = true }
core_config = { workspace = true }
core_wasm = { workspace = true }
candid = { workspace = true }
orm = { workspace = true }
orm_schema = { workspace = true }
orm_macros = { workspace = true }
types = { workspace = true }
db = { workspace = true }
db_query = { workspace = true }
mimic_common = { workspace = true }
lib_case = { workspace = true }
lib_time = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }
lib_rand = { workspace = true }
lib_cbor = { workspace = true }
snafu = { workspace = true }
