[package]
name = "api"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
config = { workspace = true }
core_schema = { workspace = true }
core_state = { workspace = true }
core_wasm = { workspace = true }
db = { workspace = true }
db_query = { workspace = true }
defer = { workspace = true }
ic = { workspace = true }
mimic_common = { workspace = true }
orm = { workspace = true }
orm_schema = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
strum = { workspace = true }
