[package]
name = "orm"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
darling = { workspace = true }
derive_more = { workspace = true }
lib_cbor = { workspace = true }
lib_ic = { workspace = true }
num-traits = { workspace = true }
orm_schema = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
strum = { workspace = true }
syn = { workspace = true }
types = { workspace = true }
