[package]
name = "orm_macros"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
darling = { workspace = true }
derive_more = { workspace = true }
ic = { workspace = true }
orm_schema = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
syn = { workspace = true }
