[package]
name = "benches"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
bencher = { workspace = true }

[[bench]]
name = "sort_key"
path = "sort_key.rs"
harness = false
