[package]
name = "benches"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
bencher = { workspace = true }

[[bench]]
name = "example"
path = "example.rs"
harness = false
