[package]
name = "core_wasm"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
ic = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
