[package]
name = "core_config"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
candid = { workspace = true }
derive_more = { workspace = true }
lib_ic = { workspace = true }
lib_cbor = { workspace = true }
mimic_derive = { workspace = true }
orm_schema = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
strum = { workspace = true }
toml = { workspace = true }
types = { workspace = true }
